#!/bin/bash

# cd ~/inner/__/js-css-html/node/_joke \
# && npm install && npm start

exists(){
  command -v "$1" >/dev/null 2>&1
}

## use forever as joke server manager
# if exists forever; then
#   echo 'MY_Info: forever has been installed'
# else
#   echo 'MY_Info: execute "npm install forever -g"'
#   npm install forever -g
# fi

## init joke server
# JOKE_PATH=~/inner/__/js-css-html/node/_joke
# if [ -d "$JOKE_PATH"/node_modules ]; then
#   echo "MY_Info: the node_modules folder already exists in $JOKE_PATH"
# else
#   echo "MY_Info: execute 'npm install' command in $JOKE_PATH"
#   cd $JOKE_PATH
#   npm install
# fi
# cd $JOKE_PATH
# printf "\n"
# echo "MY_Info: execute 'forever stopall' "
# forever stopall
# printf "\n"
# echo "MY_Info: execute 'forever start server.js' "
# forever start server.js
# printf "\n"
# echo "MY_Info: execute 'forever list' "
# forever list

# [ -d ~/Desktop/TEMPORAL/ ] && echo "DIRECTORY EXISTS" || echo "DIRECTORY DOES NOT EXIST"

printf "\n"
read -n1 -rsp $'Press any key to exit...\n'
