# bin 目录加入环境变量
# 检查: subl /etc/paths
export PATH=$HOME/bin:/usr/local/bin:$PATH

# 使用 homebrew 安装的 python2 覆盖 “系统默认的” python2
export PATH="$(brew --prefix python)/libexec/bin:$PATH"

# 使用 vim
export EDITOR='vim'
#export PS1="\u \w$"


## homebrew 加速
export HOMEBREW_BOTTLE_DOMAIN=http://7xkcej.dl1.z0.glb.clouddn.com
### brew install autojump 后提示需要添加的内容
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh


# 以下 zshrc 模板去掉了很多没用到的命令和注释
# 完整模板看这里：https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template
#
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
# Set name of the theme to load. Look in ~/.oh-my-zsh/themes/
ZSH_THEME="ys"
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)
source $ZSH/oh-my-zsh.sh


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


## proxy
### 需要安装 ShadowsocksX-NG 1.6.1 以上版本

#### 方法一: 使用 proxychains4 
alias proxy="proxychains4 -q"

#### 方法二: 设置 http_proxy ，iTerm 支持。输入 env 查看是否成功设置
#### proxyh 为 ShadowsocksX-NG 客户端 http 代理端口 (通过软件设置查看)
alias proxyh='export http_proxy=http://127.0.0.1:1087 https_proxy=http://127.0.0.1:1087'
alias proxys='export http_proxy=socks5://127.0.0.1:1080 https_proxy=socks5://127.0.0.1:1080'  
alias proxyoff='unset http_proxy https_proxy' 

#### git clone https://github.com/ant-design/ant-design.git 使用 https 协议 clone 比较快
##### 使用 阿里郎 代理（关掉其他代理服务器），先开启 阿里郎 网络加速
alion() {
    proxy=$(lsof -i -n -P | grep LISTEN |grep AliMgrSoc | tr -s ' ' | cut -d' ' -f 9)
    export http_proxy=$proxy
    export https_proxy=$proxy
    export no_proxy=localhost
    git config --global http.proxy socks5://${proxy}
    git config --global https.proxy socks5://${proxy}
    echo "需要先开启“阿里郎网络加速”，git config 代理地址为 $proxy"
}
alioff() {
    unset http_proxy
    unset https_proxy
    unset no_proxy
    git config --global --unset http.proxy
    git config --global --remove-section http
    git config --global --unset https.proxy
    git config --global --remove-section https
    echo '关闭 git config 代理'
}

# 运行 alias 查看所有别名
#alias vi="subl"
alias sz="code ~/.zshrc"
alias se="source ~/.zshrc"
alias npmr="open `npm root -g`"

# Python 虚拟环境 Virtualenv/VirtualenvWrapper
#source /usr/local/bin/virtualenvwrapper.sh

## java  参考：http://chessman-126-com.iteye.com/blog/2162466
#export JAVA_6_HOME=`/usr/libexec/java_home -v 1.6` # Mac默认 JDK 6（Mac默认自带了一个jdk6版本）
#export JAVA_7_HOME=`/usr/libexec/java_home -v 1.7` # 设置 JDK 7
export JAVA_8_HOME=`/usr/libexec/java_home -v 1.8` # 设置 JDK 8
#alias命令动态切换JDK版本
#alias jdk6="export JAVA_HOME=$JAVA_6_HOME"
#alias jdk8="export JAVA_HOME=$JAVA_8_HOME"
export JAVA_HOME=$JAVA_8_HOME #默认JDK
export CLASSPATH=.:$JAVA_HOME/lib:
export PATH=$PATH:$JAVA_HOME/bin

## android sdk
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SKD=$HOME/Library/Android/sdk
export ANDROID_SKD_HOME=$HOME/Library/Android/sdk
export PATH=${PATH}:$ANDROID_SKD_HOME/tools
export PATH=${PATH}:$ANDROID_SKD_HOME/platform-tools

## android ndk
export ANDROID_NDK=$HOME/Library/Android/android-ndk-r14b
export ANDROID_NDK_HOME=$HOME/Library/Android/android-ndk-r14b
export PATH="$ANDROID_NDK:$PATH"

## tomcat
#export PATH=$PATH:/Applications/apache-tomcat-8.0.27/bin

## maven
#export MAVEN_HOME=/usr/share/maven
#export MAVEN_HOME=/Applications/apache-maven-3.3.3
#export PATH=$PATH:$MAVEN_HOME/bin

## gradle
#export GRADLE_HOME=/Applications/gradle-2.7
#export PATH=$PATH:$GRADLE_HOME/bin

## mysql
#export PATH="/usr/local/mysql/bin:$PATH"

## sofa-sdk
#export SOFA_HOME="/Applications/sofa-sdk"
#export PATH="$SOFA_HOME:$PATH"
