#! /bin/sh

## echo ${0}
## echo $0
## echo $(pwd)

# echo "\033[32m MY_INFO: create _file.txt (y/n)?  \033[0m"
# read answer
# if [[ $answer = "" ]] || [[ $answer = "y" ]]; then
#     find . \( -name "*.md" -o -name "*.html" \) -not -path "*node_modules*" > _file.txt
#     echo "created or override the _file.txt"
# else
#     echo You quite
#     exit
# fi

printf "\n"
echo "\033[32m MY_INFO: git op (y/n)?  \033[0m"
read git_op
[[ $git_op = "n" ]] && exit

BASEDIR=$(dirname $0)
## echo $BASEDIR
cd $BASEDIR
echo "\033[32m git status \033[0m"
git st
echo "\033[32m git add -A \033[0m"
git add -A
echo "\033[32m git ci \033[0m"
git ci -a -m 'autocommit'
echo "\033[32m git push \033[0m"
git push
read -p "Press Return to Close..."